### ISSUE TITLE
Scan location modification

### ISSUE THREAD

**Issue by bogaemese** [SamsaSoftware/samsa_docs#1]
When scanning a location, we only know the zone and the line number from the ID. The locations on the line don't have their own ID. Another input field needs to be added everywhere in the forms whenever we scan a location, in which the location number will be entered. Needs to be modified in the next menus:

- Stock to Transfer Zone -> 'stocktotransfer' form, 'stocktotransferform' form (Add extra transfer location)

-Scan Pallet For Destinaton -> 'scannerpickdest' form

-Transfer Zone To Destination -> 'completetransfertolocationform' form (When adding another destination and when choosing a new destination),

**Comment by codymihai** [comment]
done
