### ISSUE TITLE
Process - Changes Sales Order Lines.

### ISSUE THREAD

**Issue by Andre-Samsa** [SamsaSoftware/samsa_docs#13]
Sales orders in NAV change frequently because customers change their order or due to out of stocks, orders are partly delivered or the truck is filled with another product mix. 

When the order is changed in NAV, the order in Samsa needs to change accourdingly.

**Comment by Andre-Samsa** [comment]
User case order VO2100075, order was put in for 10 boxes of capps on line 1000, transfer to SAMSA ok. Order was subsequently changed to 5 boxes of capps on line 1000, transfer to SAMSA. Order was changed to 5 but picking task for 10 boxes stayed open and a picking task for 5 boxes was added. Solution change status picking line to completed after update, or change the pickingtask.

**Comment by Andre-Samsa** [comment]
User case order VO2100076, instead of changing the order line, shipped 5 boxes via the old procedure, test case for using the old system next to the new. Same result, which is good, because solving the above will solve this problem too.

**Comment by relitodea** [comment]
Fixed now on Picking task id - use same Picktask while not closed - and changes when completed only
